### ISSUE TITLE
Can't resolve '@angular/cdk/scrolling' 

### ISSUE THREAD

**Issue by barocsi** [primefaces/primeng-quickstart-cli#19]
ERROR in ./node_modules/primeng/components/dropdown/dropdown.js
Module not found: Error: Can't resolve '@angular/cdk/scrolling' in 'xx\primeng\node_modules\primeng\components\dropdown'

**Comment by krmld** [comment]
run `npm install @angular/cdk --save`

**Comment by barocsi** [comment]
thanks, shouldn't be in the package json?

**Comment by tomfun** [comment]
Please add this to readme

**Comment by kahmedmujtaba** [comment]
Just install a primeng version that is OK with your cdk, other way around. But changing your cdk version for primeng could mess with other dependencies and packages that you've already installed

**Comment by nimal54** [comment]
> run `npm install @angular/cdk --save`

thankyou..

**Comment by Vafernandes** [comment]
Thanks!!!!!

**Comment by gabrielxbox** [comment]
Thanks

**Comment by Kendsar** [comment]
Thanks so much !

**Comment by Crocetti** [comment]
For me it didn't solve
Primeng "^9.0.0-rc.2"

**Comment by Sri-96** [comment]
ERROR in node_modules/@angular/cdk/coercion/array.d.ts(10,60): error TS1005: ',' expected.
node_modules/@angular/cdk/coercion/array.d.ts(10,61): error TS1005: ',' expected.
node_modules/@angular/cdk/coercion/array.d.ts(10,75): error TS1144: '{' or ';' expected.
node_modules/@angular/cdk/coercion/array.d.ts(10,77): error TS1011: An element access expression should take an argument.

**Comment by prakharism** [comment]
> ERROR in node_modules/@angular/cdk/coercion/array.d.ts(10,60): error TS1005: ',' expected.
> node_modules/@angular/cdk/coercion/array.d.ts(10,61): error TS1005: ',' expected.
> node_modules/@angular/cdk/coercion/array.d.ts(10,75): error TS1144: '{' or ';' expected.
> node_modules/@angular/cdk/coercion/array.d.ts(10,77): error TS1011: An element access expression should take an argument.

how did you resolve this ? I am facing same issue

**Comment by rgalapate** [comment]
didn't solve For angular 9.0.6
I already installed angualr/cdk

still errors:
Failed to compile entry-point primeng/dropdown (es2015 as esm2015) due to compilation errors:
node_modules/@angular/cdk/scrolling/scrolling-module.d.ts:10:22 - error NG6002: Appears in the NgModule.imports of DropdownModule, but could not be resolved to an NgModule class.

This likely means that the library (@angular/cdk/scrolling) which declares ScrollingModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

10 export declare class ScrollingModule {
                        ~~~~~~~~~~~~~~~

**Comment by mfish0005** [comment]
I would really like to use VirtualScrolling but I'm getting the same issue.  I've tried installing/uninstalling angular cdk every possible way I can think of.  Even deleting the whole node_modules folder and running `npm install` again doesn't fix it.  

I gave up and tried to use the DataView component instead but it gives me similar errors.  Since this issue is closed I think we need to open another one.

**Comment by maltainos** [comment]
Failed to compiler angular project, how to resolver it??
Error: node_modules/primeng/dropdown/dropdown.d.ts:1:42 - error TS2307: Cannot find module '@angular/cdk/scrolling' or its corresponding type declarations.

1 import { CdkVirtualScrollViewport } from '@angular/cdk/scrolling';
